### ISSUE TITLE
I cant run it

### ISSUE THREAD

**Issue by EloFran** [kellyjoe256/quizzer#1]
Hi Kellyjoe

Id like your project, and id like install it. But I dont know how enter in admin section, i used your credentials demo and admin but it no run.
I dont know very well with php. Can you help me?

thx

**Comment by kellyjoe256** [comment]
@EloFran What operating system are you using?

**Comment by EloFran** [comment]
In just moment win10 with VScode

**Comment by kellyjoe256** [comment]
I would suggest installing the following if you don't already have them

1. Install [apache](https://www.sitepoint.com/how-to-install-apache-on-windows/) - _Not necessary but you might need it later on_
1. Install [php](https://www.sitepoint.com/how-to-install-php-on-windows/)
1. Install [composer](https://devanswers.co/install-composer-php-windows-10/)
1. Install [node.js](https://www.fosstechnix.com/how-to-install-node-js-on-windows/)
1. Install [git](https://www.computerhope.com/issues/ch001927.htm)

After making sure everything is working fine, open `git-bash` and run the following commands

```bash
cd ~/Desktop
git clone https://github.com/kellyjoe256/quizzer.git
cd quizzer
cd api
composer install
cp ./.env.example ./.env
# change the database settings in the `.env` file to match your current setup 
php artisan key:generate --ansi
php artisan jwt:secret
php artisan migrate:fresh --seed
php artisan serve
# open your preferred browser and enter http://localhost:8000, to see if the api is running as it should be

# open another git-bash instance
cd ~/Desktop/quizzer
cd client
npm install
npm run serve
# open your preferred browser and type http://localhost:8080
```
I hope this helps.

**Comment by EloFran** [comment]
Thx kelly, 

when type `php artisan migrate: fresh --seed` it return: 

```
 C:\Users\eloyf\Desktop\VUE\quizzer-master\api\vendor\doctrine\dbal\lib\Doc
trine\DBAL\Driver\PDOStatement.php:129
      Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000]: General error: 1005
Can't create table `quizzer`.`quizzes` (errno: 150 "Foreign key constraint is in
correctly formed")")

  2   C:\Users\eloyf\Desktop\VUE\quizzer-master\api\vendor\doctrine\dbal\lib\Doc
trine\DBAL\Driver\PDOStatement.php:127
      PDOException::("SQLSTATE[HY000]: General error: 1005 Can't create table `q
uizzer`.`quizzes` (errno: 150 "Foreign key constraint is incorrectly formed")")
```
**Table in mysql:**
![image](https://user-images.githubusercontent.com/37640520/98684056-07d57c80-2366-11eb-8867-8ce42c01a712.png)

**Table quizzes:**
![image](https://user-images.githubusercontent.com/37640520/98684269-40755600-2366-11eb-8c0d-cdb37c0f34bb.png)


however I have ignored it because I have seen that the database if I believe it, but I cannot add an admin user, it tells me that it is not correct. Do I have to indicate somewhere besides the database the credentials?

greet

**Comment by kellyjoe256** [comment]
@EloFran I notice you are using MySQL. Please check out [this stackoverflow post](https://stackoverflow.com/questions/40863517/laravel-errno-150-foreign-key-constraint-is-incorrectly-formed) for some explanations and solutions to the issue.

**Comment by EloFran** [comment]
thx for reply,

I have changed the id to interger as the forum says. But I still can't create a **user**. I do it directly from the database, but I don't know if I need to enter the credentials somewhere else.

**My user:**

![image](https://user-images.githubusercontent.com/37640520/98742972-99b5a780-23af-11eb-89ed-235e1d9d6b03.png)

**Comment by kellyjoe256** [comment]
@EloFran May I suggest that you take a look at the following courses and books since you mentioned earlier that you are not so great with PHP so you can be able to run this project properly. [php-basics](https://codecourse.com/courses/php-basics), [php-essentials](https://codecourse.com/courses/php-essentials), [oop-with-php](https://codecourse.com/courses/practical-object-oriented-programming), [laravel-basics](https://codecourse.com/courses/laravel-basics), [javascript-basics](https://flaviocopes.com/page/javascript-handbook/), [modern-javascript](https://flaviocopes.com/page/es5-to-esnext/), and [vue](https://codecourse.com/paths/learn-vue-js).
